from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda
from langchain_core.output_parsers import JsonOutputParser

from ..azure_clients import llm


def build_json_runnable(system_prompt: str, human_template: str) -> RunnableLambda:
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system_prompt),
            ("human", human_template),
        ]
    )
    parser = JsonOutputParser()
    runnable = prompt | llm | parser
    return runnable


# ---- Event category ----
event_category_system = (
    "You are a precise Reliability Test Engineer AI assistant. "
    "Classify Test Incident Reports using Failure Definition and Scoring Criteria (FDSC). "
    "Answer ONLY from the provided context. If the answer is not in the context, say you don't know. "
    "ALWAYS return valid JSON."
)

event_category_human = """
Test Incident Report (TIR):
{tir_text}

Context snippets (numbered):
{fdsc_context}

Determine the nature of the event as exactly ONE of:
- Reliability Failure
- Non-Reliability Failure
- Other Event or Failure

Return JSON:
- event_type: one of ["Reliability Failure","Non-Reliability Failure","Other Event or Failure","Unknown"]
- reasoning: brief explanation referencing the context.
"""

event_category_runnable = build_json_runnable(event_category_system, event_category_human)


# ---- Reliability Failure ----
reliability_human = """
TIR:
{tir_text}

Context snippets (numbered):
{fdsc_context}

We already determined this is a Reliability Failure.

Classify into exactly ONE of:
- System Abort (SA)
- Essential Function Failure (EFF)
- Non-Essential Function Failure (NEFF)
- Dependent Failure
- Rapidly Recoverable Event (RRE)

If you truly cannot determine, return "Unknown".

Return JSON:
- reliability_category: one of ["SA","EFF","NEFF","Dependent Failure","RRE","Unknown"]
- reasoning: brief explanation referencing the context.
"""

reliability_runnable = build_json_runnable(event_category_system, reliability_human)


# ---- Cause-of-event ----
cause_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Assign cause of the event to ONE OR MORE of:
- Accident
- Crew/Operator
- Hardware (GFE or CFE)
- Software (GFE or CFE)
- Maintenance Personnel
- BIT
- Primary Failure (for Dependent Failures only)
- Support Equipment
- Technical Documentation and Manuals
- Training
- Unknown

Return JSON:
- cause_categories: array of categories (or ["Unknown"])
- reasoning: brief explanation referencing context.
"""

cause_runnable = build_json_runnable(event_category_system, cause_human)

# ---- Non-Reliability Failure ----
non_reliability_human = """
TIR:
{tir_text}

Context snippets (numbered):
{fdsc_context}

We already determined this is a Non-Reliability Failure.

Classify into exactly ONE of:
- Preventive Maintenance Checks and Services (PMCS)
- Scheduled Maintenance
- Routine Operating Procedure (ROP)
- FDSC-based fallback / Not Applicable

Return JSON:
- non_reliability_category: one of the categories above
- reasoning: brief explanation referencing the context.
ALWAYS return valid JSON.
"""

non_reliability_runnable = build_json_runnable(event_category_system, non_reliability_human)


# ---- Other Event or Failure ----
other_event_human = """
TIR:
{tir_text}

Context snippets (numbered):
{fdsc_context}

We already determined this is an Other Event or Failure.

Classify into exactly ONE of:
- Pre/Post-Test Checkout
- Equipment Modification
- Test Peculiar
- Test Directed Abuse
- Unrelated Damage
- Non-R&M Oriented
- Performance Limitation
- Administrative
- Not Applicable

Return JSON:
- other_event_category: one of the categories above
- reasoning: brief explanation referencing the context.
ALWAYS return valid JSON.
"""

other_event_runnable = build_json_runnable(event_category_system, other_event_human)


# ---- BIT/BITE scoring ----
bit_bite_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Determine how Built-In Test / Built-In Test Equipment (BIT/BITE) behaved for this incident.

Return JSON:
- bit_bite_scores: array containing one or more of ["False Alarm","Detection Failure","Detection Success","Isolation Failure","Isolation Success","Not Applicable"]
- reasoning: brief explanation referencing the context.
ALWAYS return valid JSON.
"""

bit_bite_runnable = build_json_runnable(event_category_system, bit_bite_human)


# ---- Maintenance demand ----
maintenance_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Identify the maintenance demand generated by this incident.

Return JSON:
- maintenance_demand: one of ["EUMD","NUMD","SMD","Not Applicable"]
- reasoning: brief explanation referencing the context.
ALWAYS return valid JSON.
"""

maintenance_runnable = build_json_runnable(event_category_system, maintenance_human)


# ---- Chargeability ----
charge_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Determine chargeability for this incident. Select all that apply.

Return JSON:
- chargeability_codes: array of codes chosen from ["CH","CS","CC","CD","CA","CM","CT","CE","CB","CZ","CU","CP","NA"]
- reasoning: brief explanation referencing the context.
ALWAYS return valid JSON.
"""

charge_runnable = build_json_runnable(event_category_system, charge_human)

# ---- Assembler ----
assembler_system = (
    "You are a precise Reliability Test Engineer AI assistant. "
    "You take structured classification outputs and produce a final rationale and markdown table. "
    "Use only values and categories from the supplied JSON. Use 'NA' when missing. "
    "ALWAYS return valid JSON."
)

assembler_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Intermediate structured outputs (JSON objects):
Event category: {event_category_json}
Reliability details: {reliability_json}
Non-reliability details: {non_reliability_json}
Other event details: {other_event_json}
Cause of event: {cause_json}
BIT/BITE scoring: {bit_bite_json}
Maintenance demand: {maintenance_json}
Chargeability: {charge_json}

Return JSON:
- rationale: string
- markdown_table: string (valid markdown table)
"""

assembler_runnable = build_json_runnable(assembler_system, assembler_human)


# ---- Reviewers & revision ----
technical_review_system = (
    "You are a strict technical reviewer for TIR classifications. "
    "You check for internal consistency and rubric compliance. ALWAYS return valid JSON."
)

technical_review_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Draft classification (JSON):
{assembled_json}

Return JSON:
- status: "pass" or "fail"
- issues: list of strings
- suggested_changes: string
"""

technical_review_runnable = build_json_runnable(technical_review_system, technical_review_human)


alignment_review_system = (
    "You are a reviewer ensuring TIR classification is grounded in the FDSC context. "
    "ALWAYS return valid JSON."
)

alignment_review_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Draft classification (JSON):
{assembled_json}

Return JSON:
- status: "pass" or "fail"
- issues: list of strings
- suggested_changes: string
"""

alignment_review_runnable = build_json_runnable(alignment_review_system, alignment_review_human)


revision_system = (
    "You are a Reliability Test Engineer assistant that updates a draft classification "
    "based on reviewer feedback. ALWAYS return valid JSON."
)

revision_human = """
TIR:
{tir_text}

Context snippets:
{fdsc_context}

Original assembled classification (JSON):
{assembled_json}

Technical review:
{technical_review_json}

Alignment review:
{alignment_review_json}

Return JSON:
- final_rationale: string
- final_markdown_table: string
"""

revision_runnable = build_json_runnable(revision_system, revision_human)
